### ISSUE TITLE
Fix date and time in API docs.

### ISSUE THREAD

**Issue by brandonlee503** [classmere/api#19]
Change the API docs to reflect that JS dates are returned for `startDate`, `endDate`, `startTime` and `endTime`.

**Comment by rutgerfarry** [comment]
I think I'll keep the start/end date format at least since this is standard JS date notation and a JSON paradigm. Class time is up for debate since dates aren't relevant for those, but it should probably be the same format for consistency, and the date part can just be ignored.

**Comment by rutgerfarry** [comment]
We can change this issue to updating the api docs to reflect these changes though.

**Comment by rutgerfarry** [comment]
Fixed by #1e4786b9

**Comment by rutgerfarry** [comment]
Fixed by 1e4786b9
